### ISSUE TITLE
./manage.py generate_encryption_key: TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by emibcn** [lanshark/django-encrypted-model-fields#7]
Hello,
I've just installed this package to a Django 2.0 project. Everything is fine, except key generation manage.py command. When I execute it, an error is raised:

```
$ ./manage.py generate_encryption_key
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/encrypted_model_fields/management/commands/generate_encryption_key.py", line 15, in handle
    self.stdout.write(key, ending=b'\n')
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 106, in write
    self._out.write(style_func(msg))
TypeError: write() argument must be str, not bytes
```

I've managed to get my key modifying Django core (not optimal, but useful):
```
$ diff django/core/management/base.py-original django/core/management/base.py
106c106
<         self._out.write(style_func(msg))
---
>         self._out.write(style_func(msg).decode(self._out.encoding))
```

I have asked there and it seems correct for Django to only expect strings and not bytes. So, with this Django version, your command should write only strings and not bytes:

encrypted_model_fields/management/commands/generate_encryption_key.py:15
```
[...]
else:
       self.stdout.write(key.decode(self.stdout.encoding), ending='\n')
```

Do you want me to do a pull request or you have a good reason to write bytes instead of strings?

Regards!

**Comment by LucasSimpson** [comment]
+1, having the same issue

**Comment by radding** [comment]
I just fixed this in PR #8: You can also use my Repo if you need this fix asap all though it is not on pip

**Comment by mwclark4453** [comment]
Thanks radding for the fix.  I was lazy and just jumped to your repo, got the committed change line and just changed it myself instead of replacing all of it.

**Comment by lanshark** [comment]
I will be pulling this in and get it merged... apparently I'm not getting email notifications on this repo.
